export const newToolsMay2026 = [

  // ── 대화형 AI / LLM ──────────────────────────────────────────────
  {
    name: 'ChatGPT',
    shortDesc: '전 세계 5억 명이 선택한 AI 대화 플랫폼',
    description: 'OpenAI의 플래그십 챗봇. GPT-4o 기반의 멀티모달 대화, 파일 분석, 코드 실행, 웹 검색까지 하나의 인터페이스에서 처리합니다. GPT Store를 통해 수천 개의 특화 GPT를 활용할 수 있습니다.',
    category: '대화형 AI · LLM',
    pricingModel: 'Freemium',
    rating: 4.92,
    tags: ['OpenAI', '챗봇', '멀티모달', 'GPT-4o'],
    isFeatured: true,
    launchUrl: 'https://chatgpt.com',
    iconUrl: 'https://logo.clearbit.com/openai.com',
    status: 'ACTIVE',
    developer: 'OpenAI',
  },
  {
    name: 'Claude',
    shortDesc: '가장 안전하고 깊이 있는 추론을 자랑하는 AI',
    description: 'Anthropic이 개발한 AI 어시스턴트. 최대 200K 토큰의 긴 문서 분석, 코딩, 글쓰기에 탁월하며 Constitutional AI 원칙으로 안전성을 극대화했습니다. Claude 3.5 Sonnet 기준 업계 최고의 코딩 능력을 보여줍니다.',
    category: '대화형 AI · LLM',
    pricingModel: 'Freemium',
    rating: 4.93,
    tags: ['Anthropic', '챗봇', '코딩', '분석'],
    isFeatured: true,
    launchUrl: 'https://claude.ai',
    iconUrl: 'https://logo.clearbit.com/anthropic.com',
    status: 'ACTIVE',
    developer: 'Anthropic',
  },
  {
    name: 'Gemini',
    shortDesc: 'Google의 멀티모달 AI — 검색과 창작을 하나로',
    description: '텍스트, 이미지, 오디오, 영상을 동시에 이해하는 Google의 차세대 AI. Gemini 2.0 Flash 기준 속도와 정확도를 모두 잡았으며 Google 생태계(Drive, Docs, Gmail)와 완벽하게 연동됩니다.',
    category: '대화형 AI · LLM',
    pricingModel: 'Freemium',
    rating: 4.88,
    tags: ['Google', '멀티모달', '검색', 'Gemini'],
    isFeatured: true,
    launchUrl: 'https://gemini.google.com',
    iconUrl: 'https://logo.clearbit.com/google.com',
    status: 'ACTIVE',
    developer: 'Google',
  },
  {
    name: 'Grok',
    shortDesc: 'X(트위터) 실시간 데이터로 무장한 xAI의 반항아',
    description: 'Elon Musk의 xAI가 개발. X 플랫폼의 실시간 데이터에 접근할 수 있어 최신 트렌드 분석에 강하며, Grok 3는 수학·과학 추론에서 최상위권 성능을 기록하고 있습니다.',
    category: '대화형 AI · LLM',
    pricingModel: 'Freemium',
    rating: 4.85,
    tags: ['xAI', 'X', '실시간', '추론'],
    isFeatured: false,
    launchUrl: 'https://grok.com',
    iconUrl: 'https://logo.clearbit.com/x.ai',
    status: 'ACTIVE',
    developer: 'xAI',
  },
  {
    name: 'DeepSeek',
    shortDesc: '중국발 오픈소스 돌풍 — GPT-4급 성능을 무료로',
    description: '中 DeepSeek이 공개한 추론 특화 모델. DeepSeek-R1은 수학·코딩 벤치마크에서 o1급 성능을 보이며 완전 오픈소스로 공개해 글로벌 AI 업계를 뒤흔들었습니다. 로컬 실행도 가능합니다.',
    category: '대화형 AI · LLM',
    pricingModel: 'Open Source',
    rating: 4.87,
    tags: ['오픈소스', '추론', '코딩', 'DeepSeek'],
    isFeatured: true,
    launchUrl: 'https://deepseek.com',
    iconUrl: 'https://logo.clearbit.com/deepseek.com',
    status: 'ACTIVE',
    developer: 'DeepSeek',
  },
  {
    name: 'Microsoft Copilot',
    shortDesc: 'Microsoft 365 전체를 관통하는 AI 어시스턴트',
    description: 'Word, Excel, PowerPoint, Teams, Outlook에 완전 내장된 AI. 회의록 자동 생성, 데이터 분석, 슬라이드 초안 작성까지 Office 생산성을 혁신합니다. GPT-4o 기반으로 웹 검색도 지원합니다.',
    category: '업무용 코파일럿 · 에이전트',
    pricingModel: 'Freemium',
    rating: 4.80,
    tags: ['Microsoft', 'Office', '생산성', '기업용'],
    isFeatured: true,
    launchUrl: 'https://copilot.microsoft.com',
    iconUrl: 'https://logo.clearbit.com/microsoft.com',
    status: 'ACTIVE',
    developer: 'Microsoft',
  },
  {
    name: 'Meta AI',
    shortDesc: 'WhatsApp·Instagram에 내장된 Llama 4 기반 AI',
    description: 'Meta의 Llama 4 Maverick 모델을 기반으로 WhatsApp, Instagram, Messenger, Facebook에 네이티브로 통합됩니다. 실시간 이미지 생성과 웹 검색을 무료로 제공합니다.',
    category: '대화형 AI · LLM',
    pricingModel: 'Free',
    rating: 4.78,
    tags: ['Meta', 'Llama', 'SNS', '무료'],
    isFeatured: false,
    launchUrl: 'https://meta.ai',
    iconUrl: 'https://logo.clearbit.com/meta.com',
    status: 'ACTIVE',
    developer: 'Meta',
  },
  {
    name: 'Mistral Chat',
    shortDesc: '유럽산 오픈소스 강자 — 빠르고 가벼운 LLM',
    description: '프랑스 스타트업 Mistral AI의 채팅 인터페이스. Mistral Large 2와 빠른 추론에 특화된 Mixtral을 포함한 여러 모델을 선택 가능. 데이터 프라이버시를 중요시하는 유럽 기업들에게 인기입니다.',
    category: '대화형 AI · LLM',
    pricingModel: 'Freemium',
    rating: 4.79,
    tags: ['오픈소스', '유럽', '경량', 'Mistral'],
    isFeatured: false,
    launchUrl: 'https://chat.mistral.ai',
    iconUrl: 'https://logo.clearbit.com/mistral.ai',
    status: 'ACTIVE',
    developer: 'Mistral AI',
  },

  // ── 코딩 / 개발 도구 ──────────────────────────────────────────────
  {
    name: 'GitHub Copilot',
    shortDesc: '2,000만 개발자가 쓰는 AI 페어 프로그래머',
    description: 'GitHub와 Microsoft가 공동 개발. VSCode, JetBrains 등 IDE에서 코드를 실시간으로 완성·제안합니다. Copilot Workspace는 이슈에서 PR까지 자율적으로 처리하는 에이전트 모드를 제공합니다.',
    category: '코딩 / 개발 도구',
    pricingModel: 'Freemium',
    rating: 4.90,
    tags: ['GitHub', 'IDE', '자동완성', 'Microsoft'],
    isFeatured: true,
    launchUrl: 'https://github.com/features/copilot',
    iconUrl: 'https://logo.clearbit.com/github.com',
    status: 'ACTIVE',
    developer: 'GitHub',
  },
  {
    name: 'Replit Agent',
    shortDesc: '브라우저에서 앱을 기획·코딩·배포까지 한 번에',
    description: '자연어로 앱 아이디어를 설명하면 Replit Agent가 코드 작성부터 패키지 설치, 환경 구성, 배포까지 자율적으로 처리합니다. 별도 로컬 환경 없이 바로 프로덕트를 완성할 수 있습니다.',
    category: '코딩 / 개발 도구',
    pricingModel: 'Freemium',
    rating: 4.82,
    tags: ['에이전트', 'IDE', '배포', 'NoCode'],
    isFeatured: false,
    launchUrl: 'https://replit.com',
    iconUrl: 'https://logo.clearbit.com/replit.com',
    status: 'ACTIVE',
    developer: 'Replit',
  },
  {
    name: 'Devin',
    shortDesc: '최초의 자율 소프트웨어 엔지니어 AI',
    description: 'Cognition AI가 개발한 세계 최초의 완전 자율 AI 소프트웨어 엔지니어. GitHub 이슈를 읽고 코드를 작성·테스트·배포까지 독립적으로 수행합니다. SWE-bench 기준 최고 성능입니다.',
    category: '코딩 / 개발 도구',
    pricingModel: 'Paid',
    rating: 4.86,
    tags: ['에이전트', '자율', '엔지니어링', 'Cognition'],
    isFeatured: true,
    launchUrl: 'https://cognition.ai',
    iconUrl: 'https://logo.clearbit.com/cognition.ai',
    status: 'ACTIVE',
    developer: 'Cognition AI',
  },
  {
    name: 'Claude Code',
    shortDesc: '터미널에서 바로 쓰는 Anthropic의 코딩 에이전트',
    description: 'Anthropic이 개발한 CLI 기반 AI 코딩 도구. 전체 코드베이스를 이해하고 자연어 명령으로 멀티 파일 편집, 테스트 실행, Git 커밋까지 처리합니다. VSCode 확장도 지원합니다.',
    category: '코딩 / 개발 도구',
    pricingModel: 'Freemium',
    rating: 4.91,
    tags: ['CLI', '에이전트', 'Anthropic', 'Terminal'],
    isFeatured: true,
    launchUrl: 'https://claude.ai/code',
    iconUrl: 'https://logo.clearbit.com/anthropic.com',
    status: 'ACTIVE',
    developer: 'Anthropic',
  },
  {
    name: 'Gemini Code Assist',
    shortDesc: 'Google이 제공하는 엔터프라이즈 AI 코딩 어시스턴트',
    description: 'Google Cloud와 Google Workspace에 연동되는 AI 코딩 어시스턴트. 1백만 토큰 컨텍스트로 거대한 코드베이스를 분석하며 Android Studio, VSCode, JetBrains에서 사용 가능합니다.',
    category: '코딩 / 개발 도구',
    pricingModel: 'Freemium',
    rating: 4.80,
    tags: ['Google', 'IDE', '엔터프라이즈', '코딩'],
    isFeatured: false,
    launchUrl: 'https://cloud.google.com/products/gemini/code-assist',
    iconUrl: 'https://logo.clearbit.com/google.com',
    status: 'ACTIVE',
    developer: 'Google',
  },

  // ── 이미지 / 디자인 ──────────────────────────────────────────────
  {
    name: 'DALL-E 3',
    shortDesc: '텍스트 묘사를 가장 정확하게 구현하는 이미지 AI',
    description: 'OpenAI의 최신 이미지 생성 모델. 자연어 지시를 극도로 정확하게 따르며 ChatGPT와 통합되어 대화 중 이미지를 즉시 생성합니다. Bing Image Creator를 통해 무료로도 사용 가능합니다.',
    category: '이미지 / 디자인',
    pricingModel: 'Freemium',
    rating: 4.85,
    tags: ['OpenAI', '이미지생성', '텍스트-이미지', 'DALL-E'],
    isFeatured: false,
    launchUrl: 'https://openai.com/dall-e-3',
    iconUrl: 'https://logo.clearbit.com/openai.com',
    status: 'ACTIVE',
    developer: 'OpenAI',
  },
  {
    name: 'Adobe Firefly',
    shortDesc: 'Photoshop에 통합된 크리에이터 친화적 생성 AI',
    description: 'Adobe Stock 데이터로 훈련해 저작권 문제에서 자유로운 기업 친화적 이미지 생성 AI. Photoshop의 생성적 채우기, Illustrator의 생성적 벡터와 통합되어 창작 워크플로를 혁신합니다.',
    category: '이미지 / 디자인',
    pricingModel: 'Freemium',
    rating: 4.83,
    tags: ['Adobe', 'Photoshop', '저작권', '디자인'],
    isFeatured: true,
    launchUrl: 'https://firefly.adobe.com',
    iconUrl: 'https://logo.clearbit.com/adobe.com',
    status: 'ACTIVE',
    developer: 'Adobe',
  },
  {
    name: 'Ideogram',
    shortDesc: '텍스트가 들어간 이미지를 가장 잘 만드는 AI',
    description: '기존 이미지 AI의 약점이었던 텍스트 렌더링을 완벽히 해결. 로고, 포스터, 배너 제작에 최적화되어 있으며 사실적인 사진과 일러스트 스타일 모두 지원합니다.',
    category: '이미지 / 디자인',
    pricingModel: 'Freemium',
    rating: 4.84,
    tags: ['텍스트', '로고', '포스터', '디자인'],
    isFeatured: false,
    launchUrl: 'https://ideogram.ai',
    iconUrl: 'https://logo.clearbit.com/ideogram.ai',
    status: 'ACTIVE',
    developer: 'Ideogram AI',
  },
  {
    name: 'Canva AI',
    shortDesc: 'AI가 완성해주는 디자인 — 비전문가도 프로 수준',
    description: 'Magic Design, Magic Edit, Magic Write 등 다양한 AI 기능을 내장. 프레젠테이션, SNS 콘텐츠, 영상 편집을 AI와 함께 단 몇 분 만에 완성합니다. 한국어 완벽 지원.',
    category: '이미지 / 디자인',
    pricingModel: 'Freemium',
    rating: 4.88,
    tags: ['디자인', 'SNS', '프레젠테이션', '한국어'],
    isFeatured: true,
    launchUrl: 'https://canva.com',
    iconUrl: 'https://logo.clearbit.com/canva.com',
    status: 'ACTIVE',
    developer: 'Canva',
  },

  // ── 글쓰기 / 콘텐츠 ──────────────────────────────────────────────
  {
    name: 'Jasper AI',
    shortDesc: '마케터를 위한 브랜드 보이스 맞춤 콘텐츠 AI',
    description: '기업의 브랜드 가이드라인과 톤을 학습해 블로그, 광고 카피, 이메일, SNS 포스트를 일관성 있게 생성합니다. 60개 이상의 템플릿과 팀 협업 기능을 제공합니다.',
    category: '글쓰기 · 콘텐츠',
    pricingModel: 'Paid',
    rating: 4.76,
    tags: ['마케팅', '카피라이팅', '브랜드', 'SEO'],
    isFeatured: false,
    launchUrl: 'https://jasper.ai',
    iconUrl: 'https://logo.clearbit.com/jasper.ai',
    status: 'ACTIVE',
    developer: 'Jasper AI',
  },
  {
    name: 'Notion AI',
    shortDesc: 'Notion 문서 안에서 바로 쓰는 AI 작성 어시스턴트',
    description: '문서 작성, 요약, 번역, 액션 아이템 추출까지 Notion 워크스페이스 안에서 바로 수행합니다. 기존 페이지를 학습해 맥락에 맞는 초안을 제안하며 한국어 지원이 우수합니다.',
    category: '글쓰기 · 콘텐츠',
    pricingModel: 'Freemium',
    rating: 4.82,
    tags: ['Notion', '문서', '생산성', '요약'],
    isFeatured: true,
    launchUrl: 'https://notion.so/product/ai',
    iconUrl: 'https://logo.clearbit.com/notion.so',
    status: 'ACTIVE',
    developer: 'Notion Labs',
  },
  {
    name: 'Grammarly',
    shortDesc: '세계 최고의 AI 글쓰기 보조 — 문법부터 설득력까지',
    description: '단순 문법 교정을 넘어 문장 명확성, 설득력, 어조까지 실시간으로 개선 제안을 합니다. 최신 버전은 이메일·문서 전체 초안을 생성해주는 Generative AI 기능을 탑재했습니다.',
    category: '글쓰기 · 콘텐츠',
    pricingModel: 'Freemium',
    rating: 4.81,
    tags: ['글쓰기', '영어', '교정', '생산성'],
    isFeatured: false,
    launchUrl: 'https://grammarly.com',
    iconUrl: 'https://logo.clearbit.com/grammarly.com',
    status: 'ACTIVE',
    developer: 'Grammarly',
  },
  {
    name: 'Copy.ai',
    shortDesc: '영업 팀을 위한 AI 콘텐츠 자동화 플랫폼',
    description: 'Go-to-Market 팀을 위해 설계된 AI 라이팅 플랫폼. 리드 아웃리치 이메일, 제품 설명, 광고 카피를 대규모로 자동 생성하는 GTM AI로 포지셔닝을 전환하고 있습니다.',
    category: '글쓰기 · 콘텐츠',
    pricingModel: 'Freemium',
    rating: 4.72,
    tags: ['카피라이팅', 'GTM', '세일즈', '마케팅'],
    isFeatured: false,
    launchUrl: 'https://copy.ai',
    iconUrl: 'https://logo.clearbit.com/copy.ai',
    status: 'ACTIVE',
    developer: 'Copy.ai',
  },

  // ── 영상 생성 / 아바타 ──────────────────────────────────────────────
  {
    name: 'Google Veo 2',
    shortDesc: 'Google의 최첨단 고해상도 영상 생성 모델',
    description: '1080p 해상도의 고품질 영상을 텍스트 또는 이미지에서 생성합니다. 복잡한 카메라 동작, 물리 법칙 시뮬레이션, 영화적 구성을 정교하게 제어할 수 있어 영상 크리에이터에게 최적입니다.',
    category: '영상 생성',
    pricingModel: 'Freemium',
    rating: 4.90,
    tags: ['Google', 'Video', '1080p', '물리'],
    isFeatured: true,
    launchUrl: 'https://deepmind.google/technologies/veo',
    iconUrl: 'https://logo.clearbit.com/google.com',
    status: 'ACTIVE',
    developer: 'Google DeepMind',
  },
  {
    name: 'Luma Dream Machine',
    shortDesc: '사실적인 물리와 부드러운 모션의 영상 생성기',
    description: 'Luma AI가 출시한 텍스트/이미지-투-비디오 모델. 유동적인 카메라 움직임과 사실적인 조명·물리를 구현합니다. Ray2 업데이트로 훨씬 향상된 시각적 품질을 제공합니다.',
    category: '영상 생성',
    pricingModel: 'Freemium',
    rating: 4.84,
    tags: ['Video', 'Luma', '물리', '모션'],
    isFeatured: false,
    launchUrl: 'https://lumalabs.ai/dream-machine',
    iconUrl: 'https://logo.clearbit.com/lumalabs.ai',
    status: 'ACTIVE',
    developer: 'Luma AI',
  },
  {
    name: 'Synthesia',
    shortDesc: 'AI 아바타가 직접 말하는 기업용 영상 제작',
    description: '실제 촬영 없이 텍스트만으로 전문 발표자가 등장하는 기업 영상을 제작합니다. 130개 언어, 200개 이상의 아바타를 지원하며 온보딩·교육·마케팅 영상 제작 시간을 90% 단축합니다.',
    category: '비디오 / 아바타',
    pricingModel: 'Paid',
    rating: 4.86,
    tags: ['아바타', '기업영상', '다국어', '교육'],
    isFeatured: true,
    launchUrl: 'https://synthesia.io',
    iconUrl: 'https://logo.clearbit.com/synthesia.io',
    status: 'ACTIVE',
    developer: 'Synthesia',
  },
  {
    name: 'Invideo AI',
    shortDesc: '프롬프트 하나로 완성되는 유튜브 영상 자동화',
    description: '아이디어나 블로그 글을 입력하면 스크립트 작성, 보이스오버, 자막, 스톡 영상 편집까지 자동으로 완성합니다. 유튜버와 마케터를 위한 영상 대량 생산에 최적화되어 있습니다.',
    category: '영상 생성',
    pricingModel: 'Freemium',
    rating: 4.77,
    tags: ['유튜브', '자동화', '마케팅', '편집'],
    isFeatured: false,
    launchUrl: 'https://invideo.io',
    iconUrl: 'https://logo.clearbit.com/invideo.io',
    status: 'ACTIVE',
    developer: 'InVideo',
  },

  // ── 오디오 / 음성 ──────────────────────────────────────────────
  {
    name: 'Descript',
    shortDesc: '영상·팟캐스트 편집을 문서 편집처럼 쉽게',
    description: '음성을 텍스트로 변환한 뒤 텍스트를 수정하면 영상이 함께 편집되는 혁신적인 워크플로를 제공합니다. AI 음성 복제(Overdub)로 녹음 실수를 타이핑으로 수정할 수 있습니다.',
    category: '오디오 / 음악',
    pricingModel: 'Freemium',
    rating: 4.85,
    tags: ['팟캐스트', '영상편집', '음성', '트랜스크립션'],
    isFeatured: false,
    launchUrl: 'https://descript.com',
    iconUrl: 'https://logo.clearbit.com/descript.com',
    status: 'ACTIVE',
    developer: 'Descript',
  },
  {
    name: 'Adobe Podcast',
    shortDesc: 'AI로 팟캐스트 음질을 스튜디오급으로 향상',
    description: 'Enhance Speech 기능 하나로 저품질 마이크 녹음을 고급 스튜디오 음질로 즉시 변환합니다. 배경 소음 제거, 에코 제거, 음성 선명도 개선까지 무료로 제공합니다.',
    category: '오디오 / 음악',
    pricingModel: 'Free',
    rating: 4.87,
    tags: ['팟캐스트', '음질향상', 'Adobe', '소음제거'],
    isFeatured: false,
    launchUrl: 'https://podcast.adobe.com',
    iconUrl: 'https://logo.clearbit.com/adobe.com',
    status: 'ACTIVE',
    developer: 'Adobe',
  },
  {
    name: 'Murf AI',
    shortDesc: '120개 언어, 1000가지 목소리의 AI 보이스오버',
    description: '프레젠테이션, 광고, e러닝 콘텐츠를 위한 AI 보이스오버 생성 플랫폼. 감정 표현이 가능한 자연스러운 음성과 강세, 속도 조절 기능으로 크리에이터와 기업에 최적입니다.',
    category: '오디오 / 음악',
    pricingModel: 'Freemium',
    rating: 4.79,
    tags: ['TTS', '보이스오버', '다국어', '크리에이터'],
    isFeatured: false,
    launchUrl: 'https://murf.ai',
    iconUrl: 'https://logo.clearbit.com/murf.ai',
    status: 'ACTIVE',
    developer: 'Murf AI',
  },
  {
    name: 'Stable Audio',
    shortDesc: '텍스트로 배경음악과 효과음을 만드는 음악 AI',
    description: 'Stability AI가 출시한 오디오 생성 모델. 장르, BPM, 악기, 분위기를 텍스트로 지정하면 저작권 걱정 없는 고품질 배경음악과 효과음을 생성합니다.',
    category: '오디오 / 음악',
    pricingModel: 'Freemium',
    rating: 4.75,
    tags: ['음악', 'BGM', '효과음', 'StabilityAI'],
    isFeatured: false,
    launchUrl: 'https://stableaudio.com',
    iconUrl: 'https://logo.clearbit.com/stability.ai',
    status: 'ACTIVE',
    developer: 'Stability AI',
  },

  // ── 검색 / 리서치 ──────────────────────────────────────────────
  {
    name: 'Perplexity AI',
    shortDesc: '출처가 명확한 AI 답변 — 구글 검색의 강력한 대안',
    description: '검색 결과를 요약해 한 번에 답변하고, 각 사실의 출처를 명확히 표시합니다. Pro Search는 여러 단계의 심층 검색을 수행하며 최신 뉴스부터 학술 논문까지 분석합니다.',
    category: 'AI 브라우저 · 리서치',
    pricingModel: 'Freemium',
    rating: 4.91,
    tags: ['검색', '리서치', '출처', 'Perplexity'],
    isFeatured: true,
    launchUrl: 'https://perplexity.ai',
    iconUrl: 'https://logo.clearbit.com/perplexity.ai',
    status: 'ACTIVE',
    developer: 'Perplexity AI',
  },
  {
    name: 'Elicit',
    shortDesc: '수백 편의 논문을 동시에 분석하는 AI 연구 어시스턴트',
    description: '연구 질문을 입력하면 수천 편의 학술 논문에서 관련 데이터를 추출·비교합니다. 표로 정리된 문헌 고찰을 자동 생성해 연구자들의 리뷰 시간을 수십 배 단축시킵니다.',
    category: 'AI 브라우저 · 리서치',
    pricingModel: 'Freemium',
    rating: 4.83,
    tags: ['논문', '학술', '연구', '문헌분석'],
    isFeatured: false,
    launchUrl: 'https://elicit.com',
    iconUrl: 'https://logo.clearbit.com/elicit.com',
    status: 'ACTIVE',
    developer: 'Ought',
  },

  // ── 교육 ──────────────────────────────────────────────
  {
    name: 'Khanmigo',
    shortDesc: '칸아카데미의 소크라테스식 AI 학습 멘토',
    description: 'Khan Academy가 개발한 AI 튜터. 답을 직접 주지 않고 소크라테스식 질문으로 학습자 스스로 문제를 해결하도록 유도합니다. 수학, 과학, 코딩, 역사 등 전 과목을 지원합니다.',
    category: '교육 AI',
    pricingModel: 'Freemium',
    rating: 4.82,
    tags: ['교육', '튜터', '학습', 'Khan Academy'],
    isFeatured: false,
    launchUrl: 'https://khanacademy.org/khan-labs',
    iconUrl: 'https://logo.clearbit.com/khanacademy.org',
    status: 'ACTIVE',
    developer: 'Khan Academy',
  },
  {
    name: 'Duolingo AI',
    shortDesc: 'AI 캐릭터와 실제 대화로 배우는 언어학습',
    description: '기존 Duolingo에 AI가 더해져 가상의 원어민 캐릭터와 실제 대화 연습이 가능합니다. Video Call 기능으로 AI와 화상 통화 형식의 회화 연습을 할 수 있으며 즉각적인 피드백을 제공합니다.',
    category: '교육 AI',
    pricingModel: 'Freemium',
    rating: 4.78,
    tags: ['언어학습', '회화', 'AI튜터', '게이미피케이션'],
    isFeatured: false,
    launchUrl: 'https://duolingo.com',
    iconUrl: 'https://logo.clearbit.com/duolingo.com',
    status: 'ACTIVE',
    developer: 'Duolingo',
  },

  // ── AI 검색 엔진 / 브라우저 ──────────────────────────────────────────────
  {
    name: 'You.com',
    shortDesc: '개인화된 AI 검색 + 연구 보고서 자동 생성',
    description: '검색 결과를 AI로 요약할 뿐 아니라, Research Mode에서 심층 보고서를 자동으로 작성합니다. 코딩, 수학, 이미지 생성 모드 전환이 가능해 올인원 AI 도구로 진화 중입니다.',
    category: 'AI 브라우저 · 리서치',
    pricingModel: 'Freemium',
    rating: 4.78,
    tags: ['검색', '보고서', '리서치', '코딩'],
    isFeatured: false,
    launchUrl: 'https://you.com',
    iconUrl: 'https://logo.clearbit.com/you.com',
    status: 'ACTIVE',
    developer: 'You.com',
  },

  // ── 특화 도구 ──────────────────────────────────────────────
  {
    name: 'Framer AI',
    shortDesc: '텍스트로 웹사이트를 직접 디자인하는 AI 빌더',
    description: '웹사이트 내용과 스타일을 자연어로 설명하면 Framer AI가 반응형 디자인과 인터랙션까지 완성된 웹사이트를 즉시 생성합니다. 퍼블리시까지 코드 한 줄 없이 가능합니다.',
    category: '코딩 / 개발 도구',
    pricingModel: 'Freemium',
    rating: 4.83,
    tags: ['웹빌더', 'NoCode', '디자인', '반응형'],
    isFeatured: false,
    launchUrl: 'https://framer.com/ai',
    iconUrl: 'https://logo.clearbit.com/framer.com',
    status: 'ACTIVE',
    developer: 'Framer',
  },
  {
    name: 'Gamma',
    shortDesc: '프롬프트 한 줄로 완성하는 AI 프레젠테이션',
    description: '주제만 입력하면 구조 잡힌 슬라이드 덱, 문서, 웹페이지를 자동으로 생성합니다. 파워포인트 방식의 틀에 얽매이지 않는 현대적인 카드 형식 디자인과 AI 기반 콘텐츠 보완이 특징입니다.',
    category: '글쓰기 · 콘텐츠',
    pricingModel: 'Freemium',
    rating: 4.86,
    tags: ['프레젠테이션', 'PPT', '문서', '슬라이드'],
    isFeatured: true,
    launchUrl: 'https://gamma.app',
    iconUrl: 'https://logo.clearbit.com/gamma.app',
    status: 'ACTIVE',
    developer: 'Gamma',
  },
  {
    name: 'Runway Gen-4',
    shortDesc: '일관된 캐릭터와 세계관을 유지하는 차세대 영상 AI',
    description: 'Runway의 최신 영상 생성 모델. Gen-4는 인물의 얼굴, 의상, 배경 환경의 일관성을 여러 씬에 걸쳐 유지합니다. 영화·광고 제작사가 실제 프로덕션에 도입하고 있습니다.',
    category: '영상 생성',
    pricingModel: 'Paid',
    rating: 4.89,
    tags: ['Video', '일관성', '영화', 'Runway'],
    isFeatured: true,
    launchUrl: 'https://runwayml.com',
    iconUrl: 'https://logo.clearbit.com/runwayml.com',
    status: 'ACTIVE',
    developer: 'Runway',
  },
  {
    name: 'Windsurf Wave',
    shortDesc: 'Windsurf IDE의 자율 다단계 코딩 에이전트 모드',
    description: 'Codeium의 Windsurf에 탑재된 Wave 에이전트 모드. 단순 자동완성을 넘어 복잡한 멀티 파일 리팩토링, 버그 수정, 테스트 작성을 자율적으로 계획하고 실행합니다.',
    category: '코딩 / 개발 도구',
    pricingModel: 'Freemium',
    rating: 4.84,
    tags: ['IDE', '에이전트', '자율', 'Codeium'],
    isFeatured: false,
    launchUrl: 'https://codeium.com/windsurf',
    iconUrl: 'https://logo.clearbit.com/codeium.com',
    status: 'ACTIVE',
    developer: 'Codeium',
  },
  {
    name: 'n8n AI',
    shortDesc: '개발자를 위한 셀프 호스팅 AI 워크플로 자동화',
    description: '오픈소스 기반의 워크플로 자동화 도구에 AI 에이전트 기능을 결합. 400개 이상의 앱 연동을 지원하며 완전한 셀프 호스팅이 가능해 기업 데이터를 외부에 노출하지 않고 자동화를 구축합니다.',
    category: '에이전트 빌더 · 워크플로',
    pricingModel: 'Open Source',
    rating: 4.80,
    tags: ['오픈소스', '자동화', '셀프호스팅', '워크플로'],
    isFeatured: false,
    launchUrl: 'https://n8n.io',
    iconUrl: 'https://logo.clearbit.com/n8n.io',
    status: 'ACTIVE',
    developer: 'n8n',
  },
  {
    name: 'Perplexity Deep Research',
    shortDesc: '전문가급 리서치 보고서를 30분 만에 자동 작성',
    description: 'Perplexity의 Deep Research 모드는 수백 개의 웹 소스를 자율적으로 탐색하고 전문가 수준의 심층 리서치 보고서를 PDF로 생성합니다. 투자 분석, 시장 조사, 학술 리뷰에 활용됩니다.',
    category: 'AI 브라우저 · 리서치',
    pricingModel: 'Paid',
    rating: 4.89,
    tags: ['리서치', '보고서', '심층분석', 'Perplexity'],
    isFeatured: true,
    launchUrl: 'https://perplexity.ai',
    iconUrl: 'https://logo.clearbit.com/perplexity.ai',
    status: 'ACTIVE',
    developer: 'Perplexity AI',
  },
  {
    name: 'OpenAI o3',
    shortDesc: '추론·수학·코딩 전용 최강 성능 모델',
    description: 'OpenAI의 차세대 추론 특화 모델. 복잡한 수학 문제, 과학 추론, 코딩 챌린지에서 역대 최고 점수를 기록합니다. 생각을 단계적으로 전개하는 chain-of-thought로 난이도 높은 문제를 해결합니다.',
    category: '대화형 AI · LLM',
    pricingModel: 'Paid',
    rating: 4.94,
    tags: ['추론', '수학', '코딩', 'OpenAI'],
    isFeatured: true,
    launchUrl: 'https://openai.com',
    iconUrl: 'https://logo.clearbit.com/openai.com',
    status: 'ACTIVE',
    developer: 'OpenAI',
  },
  {
    name: 'Slack AI',
    shortDesc: 'Slack 채널의 무한 대화를 즉시 요약하는 AI',
    description: 'Slack에 내장된 AI 기능. 오랜 시간 쌓인 채널 대화를 요약하고, 답장 초안을 작성하며, 워크스페이스 전체에서 정보를 검색합니다. 미팅 복귀 후 놓친 내용을 즉시 파악할 수 있습니다.',
    category: '업무용 코파일럿 · 에이전트',
    pricingModel: 'Paid',
    rating: 4.77,
    tags: ['Slack', '채팅요약', '생산성', '협업'],
    isFeatured: false,
    launchUrl: 'https://slack.com/features/ai',
    iconUrl: 'https://logo.clearbit.com/slack.com',
    status: 'ACTIVE',
    developer: 'Salesforce (Slack)',
  },
];
